services:
- type: web
  name: mysql
  plan: standard
  env: docker
  autoDeploy: false
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: mysql

envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: felix
  - key: MYSQL_PASSWORD
    value: lars
  - key: MYSQL_ROOT_PASSWORD
    value: admin_password
